name: Extension Testing / openbao-configurator

on:
  pull_request:
    paths:
      - "openbao-configurator/**"
      - ".github/workflows/extension-testing.yml"
      - ".github/workflows/extension-testing-openbao-configurator.yml"
  workflow_dispatch:

permissions:
  contents: read

run-name: Test openbao-configurator

jobs:
  test:
    uses: ./.github/workflows/extension-testing.yml
    with:
      extension: openbao-configurator
