name: Extension Testing / libvirt-vm-pool

on:
  pull_request:
    paths:
      - "libvirt-vm-pool/**"
      - ".github/workflows/extension-testing.yml"
      - ".github/workflows/extension-testing-libvirt-vm-pool.yml"
  workflow_dispatch:

permissions:
  contents: read

run-name: Test libvirt-vm-pool

jobs:
  test:
    uses: ./.github/workflows/extension-testing.yml
    with:
      extension: libvirt-vm-pool
